### PR TITLE
respect the DoNotDiscover annotation

### PR DESCRIPTION
**Pull request by maiflai**

### CODE REVIEW

**Review by giurim — APPROVED** [review]
Thank you, great improvement!

**Comment by maiflai** [comment]
thanks - it would be great to be able to use it, is there any upcoming release that might include this change?

**Comment by giurim** [comment]
I will try to release the change ASAP (this week)

**Comment by maiflai** [comment]
great, thanks very much

**Comment by maiflai** [comment]
Looks good, thanks for the quick turnaround!

There’s a minor unrelated  problem with a certain type of test constructor, but I have a workaround for now and will see if I can work out a fix.

**Comment by giurim** [comment]
Thank you for the PR. You are.more than welcome to file an issue as well if
you find bugs or you see opportunities for improvement.

**Pull request merged**
